spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_DEV:allbs-mysql}:3306/allbs
    username: root
    password: ${PASS_COMMON_2:123456}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
  data:
    redis:
      database: 1
      host: ${REDIS_HOST_DEV:127.0.0.1}
      port: 6379
      password: ${REDIS_PWD_DEV:123456}
      timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: cn.allbs.admin.config.handler

jwt:
  expire-time: 43200 #过期时间秒
  refresh-time: 43200 #刷新时间秒
  sign-key: allbs # 签名

security:
  ignore-urls:
    - /v3/api-docs/**
    - /doc.html
    - /webjars/**
    - /druid/**
    - /static/**
    - /configuration/ui
    - /swagger-resources/**

swagger:
  title: spring boot3新工程模板
  description: 使用spring boot3 + jdk17重新搭建的工程模板
  version: 1.0
  securitySchemes:
    token:
      type: APIKEY  # 类型
      in: HEADER    # 放header里面
      name: token # header-key
  servers:
    - url: http://127.0.0.1:8888 # 自定义服务器 URL，如部署在docker中时可以配置
      description: 本地服务器
springdoc:
  api-docs:
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: cn.allbs.admin.controller
  # 配置需要生成接口文档的接口路径，如果增加了该节点，那么只将/user开头的接口文档生成出来
  # paths-to-match: /user/**
